export const COLOMBIAN_CAR_MAKES: { [make: string]: string[] } = {
    'Chevrolet': ['Spark', 'Onix', 'Sail', 'Tracker', 'Captiva', 'D-Max', 'Joy', 'Equinox'],
    'Renault': ['Kwid', 'Sandero', 'Logan', 'Stepway', 'Duster', 'Oroch', 'Captur'],
    'Mazda': ['2', '3', 'CX-5', 'CX-30', 'CX-50', 'BT-50'],
    'Nissan': ['March', 'Versa', 'Kicks', 'Frontier', 'X-Trail', 'Qashqai', 'Altima'],
    'Kia': ['Picanto', 'Rio', 'Soluto', 'Sportage', 'Seltos', 'Niro'],
    'Hyundai': ['i10', 'i20', 'i30', 'Tucson', 'Santa Fe', 'Creta', 'HB20'],
    'Toyota': ['Yaris', 'Corolla', 'RAV4', 'Hilux', 'Prado', 'Fortuner', 'Prius'],
    'Ford': ['Fiesta', 'Focus', 'EcoSport', 'Escape', 'Explorer', 'Ranger', 'F-150'],
    'Volkswagen': ['Polo', 'Golf', 'Jetta', 'Tiguan', 'Amarok', 'T-Cross', 'Nivus'],
    'Suzuki': ['Swift', 'SX4', 'Vitara', 'Jimny', 'Grand Vitara', 'Baleno'],
    'Mitsubishi': ['Lancer', 'Outlander', 'Montero', 'Triton', 'ASX', 'Eclipse Cross'],
    'Honda': ['City', 'Civic', 'CR-V', 'Pilot', 'Accord', 'HR-V', 'Fit'],
    'BMW': ['Serie 1', 'Serie 3', 'Serie 5', 'X1', 'X3', 'X5', 'X6', 'Z4'],
    'Mercedes-Benz': ['Clase A', 'Clase C', 'Clase E', 'GLA', 'GLC', 'GLE', 'GLS', 'Clase S'],
    'Audi': ['A1', 'A3', 'A4', 'A6', 'Q3', 'Q5', 'Q7', 'TT', 'R8'],
    'Volvo': ['XC40', 'XC60', 'XC90', 'S60', 'S90', 'V60', 'V90'],
    'Lexus': ['IS', 'ES', 'GS', 'LS', 'NX', 'RX', 'GX', 'LX'],
    'Infiniti': ['Q50', 'Q60', 'QX50', 'QX60', 'QX80'],
    'Acura': ['ILX', 'TLX', 'RLX', 'RDX', 'MDX', 'NSX'],
    'Genesis': ['G70', 'G80', 'G90', 'GV70', 'GV80'],
    'Lincoln': ['MKZ', 'Continental', 'MKC', 'MKT', 'Navigator'],
    'Cadillac': ['ATS', 'CTS', 'XTS', 'XT4', 'XT5', 'XT6', 'Escalade'],
    'Buick': ['Encore', 'Envision', 'Enclave', 'LaCrosse', 'Regal'],
    'GMC': ['Terrain', 'Acadia', 'Yukon', 'Sierra', 'Canyon'],
    'Chrysler': ['300', 'Pacifica', 'Voyager'],
    'Dodge': ['Charger', 'Challenger', 'Durango', 'Journey', 'Grand Caravan'],
    'Jeep': ['Compass', 'Cherokee', 'Grand Cherokee', 'Wrangler', 'Renegade', 'Gladiator'],
    'Ram': ['1500', '2500', '3500', 'ProMaster', 'ProMaster City'],
    'Fiat': ['500', '500L', '500X', 'Tipo', 'Doblo', 'Ducato'],
    'Alfa Romeo': ['Giulia', 'Stelvio', '4C'],
    'Maserati': ['Ghibli', 'Quattroporte', 'Levante', 'GranTurismo'],
    'Ferrari': ['488', 'F8', 'SF90', 'Roma', 'Portofino', '812'],
    'Lamborghini': ['Huracán', 'Aventador', 'Urus'],
    'Bentley': ['Continental', 'Flying Spur', 'Bentayga'],
    'Rolls-Royce': ['Ghost', 'Wraith', 'Dawn', 'Cullinan', 'Phantom'],
    'Aston Martin': ['Vantage', 'DB11', 'DBS', 'DBX'],
    'McLaren': ['540C', '570S', '600LT', '720S', 'GT', 'Artura'],
    'Porsche': ['718', '911', 'Panamera', 'Macan', 'Cayenne', 'Taycan'],
    'Lotus': ['Elise', 'Exige', 'Evora', 'Emira'],
    'Jaguar': ['XE', 'XF', 'XJ', 'F-PACE', 'E-PACE', 'I-PACE'],
    'Land Rover': ['Discovery Sport', 'Discovery', 'Range Rover Evoque', 'Range Rover Velar', 'Range Rover', 'Defender'],
    'Mini': ['Cooper', 'Cooper S', 'Cooper SE', 'Countryman', 'Clubman'],
    'Smart': ['Fortwo', 'Forfour'],
    'Tesla': ['Model S', 'Model 3', 'Model X', 'Model Y', 'Roadster', 'Cybertruck'],
    'Rivian': ['R1T', 'R1S'],
    'Lucid': ['Air'],
    'Polestar': ['1', '2'],
    'BYD': ['Tang', 'Song', 'Han', 'Qin'],
    'Geely': ['Coolray', 'Atlas', 'Emgrand'],
    'Great Wall': ['Haval H2', 'Haval H6', 'Haval H9', 'Wingle'],
    'Chery': ['Tiggo', 'Arrizo', 'QQ'],
    'JAC': ['T40', 'T50', 'T60', 'T80'],
    'BAIC': ['X25', 'X35', 'X55', 'X65'],
    'Changan': ['CS15', 'CS35', 'CS55', 'CS75', 'CS95'],
    'Haval': ['H2', 'H6', 'H9', 'F5', 'F7'],
    'MG': ['3', '5', '6', 'HS', 'ZS', 'RX5'],
    'Maxus': ['G10', 'T60', 'D60', 'D90'],
    'Foton': ['Sauvana', 'Tunland', 'Saga'],
    'Isuzu': ['D-Max', 'MU-X'],
    'Subaru': ['Impreza', 'Legacy', 'Outback', 'Forester', 'XV', 'WRX', 'BRZ'],
    'Mitsubishi Fuso': ['Canter', 'Rosa', 'Fighter'],
    'Hino': ['300', '500', '700'],
    'UD Trucks': ['Quester', 'Croner', 'Kazet'],
    'Iveco': ['Daily', 'Eurocargo', 'Stralis'],
    'Scania': ['P', 'G', 'R', 'S'],
    'Volvo Trucks': ['FH', 'FM', 'FMX', 'VNL', 'VNR'],
    'MAN': ['TGL', 'TGM', 'TGS', 'TGX'],
    'Mercedes-Benz Trucks': ['Atego', 'Actros', 'Antos', 'Arocs'],
    'DAF': ['LF', 'CF', 'XF', 'XF105'],
    'Renault Trucks': ['T', 'C', 'K', 'D'],
    'Iveco Bus': ['Crossway', 'Urbanway', 'Crealis'],
    'Mercedes-Benz Bus': ['Citaro', 'Conecto', 'Intouro'],
    'Volvo Bus': ['7900', '8900', '9900', 'B12'],
    'Scania Bus': ['Citywide', 'Interlink', 'Fencer'],
    'MAN Bus': ['Lion\'s City', 'Lion\'s Intercity', 'Lion\'s Coach'],
    'DAF Bus': ['LF', 'CF', 'XF'],
    'Renault Bus': ['Master', 'Master ZE', 'Citybus'],
};
